version: '3.9'
services:
    club:
        build: .
        container_name: club
        restart: always
        env_file: .env
        command: npm run dev
        volumes:
            - .:/app
        ports:
            - "4100:4000"
        networks:
            - club_network

    club_database:
        image: "mongo"
        container_name: club_database
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb:/data/db
        networks:
            - club_network

volumes:
    mongodb:


networks:
    club_network:
        driver: bridge
