version: '3.9'
services: 
    club:
      build:
          context: .
      env_file: ./.env
      command: yarn start
      volumes: 
          - .:/app/
          - /app/node_modules
      ports:
          - "4004:4000"
      expose:
          - "4004"